version: '3'

services:
  # Golang API
  api:
    build: build/api/
    image: 'bobba/api'
    container_name: 'bobba_go_api'
    volumes: 
      - ./api:/data
    ports:
      - "9000:8000"
    depends_on:
      - db
    # Unable to pass the .env file to the container
    environment:
      MYSQL_DATABASE: ${database}
      MYSQL_USER: ${username}
      MYSQL_PASSWORD: ${password}
      MYSQL_PORT: ${port}
      MYSQL_HOST: ${host}
  
  # Front VueJS
  web:
    build: build/node/
    image: 'bobba/front'
    container_name: 'bobba_vue_front'
    volumes:
      - ./front:/data
    ports:
      - "8080:8080"

  # MySQL Database
  db:
    image: mysql:latest
    container_name: 'bobba_database'
    ports:
      - "3306:3306"
    volumes:
      - ./sql/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: ${root_password}
      MYSQL_DATABASE: ${database}
      MYSQL_USER: ${username}
      MYSQL_PASSWORD: ${password}