# Deployment for the api
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.stateful.name }}
  labels:
    helm.sh/chart: {{ include "bobba-db-chart.chart" . }}
    app: {{ .Values.stateful.name }}
    tier: {{ .Values.stateful.tier }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      helm.sh/chart: {{ include "bobba-db-chart.chart" . }}
      app: {{ .Values.stateful.name }}
      tier: {{ .Values.stateful.tier }}
  serviceName: {{ .Values.stateful.serviceName }}
  template:
    metadata:
      labels:
        helm.sh/chart: {{ include "bobba-db-chart.chart" . }}
        app: {{ .Values.stateful.name }}
        tier: {{ .Values.stateful.tier }}
    spec:
      containers:
        - name: {{ .Values.stateful.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.stateful.port }}
              protocol: TCP
          volumeMounts:
            - name: {{ .Values.volumes.name }}
              mountPath: {{ .Values.volumes.mountPath }}
  volumeClaimTemplates: {{- include "bobba-helm-chart.volumes" . | nindent 4 }}
          