# Deployment configuration
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    helm.sh/chart: {{ include "bobba-api-chart.chart" . }}
    app: {{ .Values.deployment.name }}
    tier: {{ .Values.deployment.tier }}
spec:
  replicas: {{ .Values.deployment.replicasCount }}
  selector:
    matchLabels:
      helm.sh/chart: {{ include "bobba-api-chart.chart" . }}
      app: {{ .Values.deployment.name }}
      tier: {{ .Values.deployment.tier }}
  template:
    metadata:
      labels:
        helm.sh/chart: {{ include "bobba-api-chart.chart" . }}
        app: {{ .Values.deployment.name }}
        tier: {{ .Values.deployment.tier }}
    spec:
      containers:
        - name: {{ .Values.deployment.name }}
          {{- if .Values.env }}
            env: {{- include "bobba-api-chart.environment" . | nindent 4 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.deployment.port }}
              protocol: TCP