kind: Service
apiVersion: v1
metadata:
  name: bobba-api
spec:
  type: NodePort
  selector:
    app: bobba-api
    tier: backend
  ports:
  # Expose outside of the cluster
  - nodePort: 31320
    protocol: TCP
    # port expose to the cluster
    port: 80
    # Port of the pods
    targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bobba-api
  labels:
    app: bobba-api
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bobba-api
      tier: backend
  template:
    metadata:
      labels:
        app: bobba-api
        tier: backend
    spec:
      containers:
      - name: bobba-api
        image: gcr.io/kubernetes-demo-232217/sesame_api:v1
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8000
        args:
          - sh
          - start.sh