apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: temporary
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: temporary
            image: sesame_minikube_second
            imagePullPolicy: Never
            args:
            - sh
            - startup.sh
            - kube
            - temporary
          restartPolicy: OnFailure
