apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: select
spec:
  schedule: "*/30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: select
            image: sesame_minikube
            imagePullPolicy: Never
            args:
            - go
            - run
            - select/select.go
          restartPolicy: OnFailure
