apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: bruteforce
spec:
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: bruteforce
            image: sesame_minikube
            imagePullPolicy: Never
            args:
            - go
            - run
            - bruteforce/bruteforce.go
          restartPolicy: OnFailure
