{{- define "bobba-helm-chart.environment.prod" -}}
{{- if eq .Values.deployment.app "bobba-vue" -}}
- name: DEPLOYMENT
  value: gcloud
{{- else -}}
- name: NODE_NAME
  valueFrom:
    fieldRef:
      fieldPath: spec.nodeName
- name: MYSQL_HOST
  value: 127.0.0.1
- name: MYSQL_USER
  valueFrom:
    secretKeyRef:
      name: cloudsql-db-credentials
      key: username
- name: MYSQL_PASSWORD
  valueFrom:
    secretKeyRef:
      name: cloudsql-db-credentials
      key: password   
{{- end -}}
{{- end -}}