apiVersion: apps/v1
kind: Deployment
metadata:
  name: bobba-api
  labels:
    app: bobba-api
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bobba-api
      tier: backend
  template:
    metadata:
      labels:
        app: bobba-api
        tier: backend
    spec:
      containers:
      - name: bobba-api
        image: sesame_api:latest
        imagePullPolicy: Never
        ports:
          - containerPort: 8000