apiVersion: apps/v1
kind: Deployment
metadata:
  name: bobba-vue
  labels:
    app: bobba-vue
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bobba-vue
      tier: frontend
  template:
    metadata:
      labels:
        app: bobba-vue
        tier: frontend
    spec:
      containers:
      - name: bobba-front
        image: sesame_front:latest
        imagePullPolicy: Never
        ports:
          - containerPort: 8080
        args:
          - sh
          - start.sh