# Values for the prod of bobba-vue.
# environment
environment:
  prod: true

# Use by the service
service:
  name: bobba-vue-service
  type: LoadBalancer
  port: 80
  targetPort: 8080

# Use by the deployment
deployment:
  app: bobba-vue
  name: bobba-vue
  tier: frontend
  replicasCount: 9
  port: 8080
  args: true

# database activation
db:
  enabled: false

# Image use by the deployment
image:
  repository: gcr.io/kubernetes-demo-232217/sesame_front
  tag: v3.1
  pullPolicy: IfNotPresent

# Ingress
ingress:
  enabled: false

# Args
env: true
projectID: Front VueJS