# Default values for bobba-api-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Use by the service
service:
  name: bobba-api-service
  type: NodePort
  port: 80
  targetPort: 8000
  nodePort: 31320

# Use by the deployment
deployment:
  app: bobba-api
  name: bobba-api
  tier: backend
  replicasCount: 10
  port: 8000

# database activation
db:
  enabled: false

# Image use by the deployment
image:
  repository: gcr.io/kubernetes-demo-232217/sesame_api
  tag: v3.3
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  name: bobba-api-ingress
  ip: bobba-api-ip
  path: /*

env: true
projectID: API Golang