# Default values for bobba-api-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

environment:
  prod: false

# Use by the service
service:
  name: bobba-api-service
  type: NodePort
  port: 80
  targetPort: 8000
  nodePort: 31320

# Use by the deployment
deployment:
  app: bobba-api
  name: bobba-api
  tier: backend
  replicasCount: 5
  port: 8000

# database activation
db:
  enabled: true

# Image use by the deployment
image:
  repository: sesame_api
  tag: latest
  pullPolicy: Never

ingress:
  enabled: false
  name: bobba-api-ingress
  ip: bobba-api-ip
  path: /*

projectID: API Golang