kind: Service
apiVersion: v1
metadata:
  name: bobba-vue
spec:
  type: NodePort
  selector:
    app: bobba-vue
    tier: frontend
  ports:
  - nodePort: 31317
    protocol: TCP
    port: 8080
    targetPort: 8080
